dist: bionic
addons:
  chrome: stable
language: python
python:
    - "3.6"

install:
  - "pip install -r requirements.txt"
  - "wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip; unzip chromedriver_linux64.zip -d chromedriver; export PATH=$PATH:`pwd`/chromedriver"


script:
    - "flake8 ."
    - "python -m pytest"
    - "python freeze.py"
