[project]
name = "ocdsextensionexplorer"
version = "0.0.0"

[project.entry-points."babel.extractors"]
tag = "extension_explorer.extract:extract_tag"

[tool.setuptools]
packages = ["extension_explorer"]

[tool.isort]
profile = "black"
line_length = 119
