[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "ocdsextensionexplorer"
version = "0.0.0"
license = {text = "BSD"}

[project.entry-points."babel.extractors"]
tag = "extension_explorer.extract:extract_tag"

[tool.isort]
profile = "black"
line_length = 119
