name: Deploy
on:
  workflow_dispatch:
  schedule:
    - cron: "11 2 * * *"
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-python@v6.3.0
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: '**/requirements*.txt'
      - run: pip install -r requirements.txt
      - run: pysassc extension_explorer/static/lib/scss/theme.scss > extension_explorer/static/css/theme.css
      - working-directory: extension_explorer
        run: pybabel compile -f -d locale
      - name: Build
        env:
          # For the ocdsextensionregistry package to use the GitHub API to get the organization name.
          OCDS_GITHUB_ACCESS_TOKEN: ${{ secrets.OCDS_GITHUB_ACCESS_TOKEN }}
        shell: bash
        run: |
          git clone https://github.com/open-contracting/ocds-extensions-translations.git
          ocdsextensionregistry generate-data-file --locale-dir ocds-extensions-translations/locale > extension_explorer/data/extensions.json
          python freeze.py
          echo "/*
            Content-Security-Policy: default-src 'self'; script-src 'self' https://cdn.usefathom.com/script.js; img-src 'self' data: https:; object-src 'none'; worker-src 'none'; frame-ancestors 'none'
            Strict-Transport-Security: max-age=31536000; includeSubDomains; preload" > extension_explorer/build/_headers
      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: extension_explorer/build
          cname: extensions.open-contracting.org
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
