name: Deploy
on:
  schedule:
    - cron: "11 2 * * *"
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - name: Build
        env:
          OCDS_GITHUB_ACCESS_TOKEN: ${{ secrets.OCDS_GITHUB_ACCESS_TOKEN }}
        run: |
          git clone https://github.com/open-contracting/ocds-extensions-translations.git
          ocdsextensionregistry generate-data-file --locale-dir ocds-extensions-translations/locale > extension_explorer/data/extensions.json
          python freeze.py
      - name: Compile translations
        run: |
          cd extension_explorer
          pybabel compile -d translations -f
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: extension_explorer/build
          cname: extensions.open-contracting.org
          force_orphan: true
