name: Translations
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: '**/requirements*.txt'
      - name: Install translate-toolkit
        run: |
          sudo apt update
          sudo apt install translate-toolkit
      - run: pip install -r requirements.txt
      - name: Update catalogs
        working-directory: extension_explorer
        run: |
          pybabel extract -F babel.cfg -o messages.pot .
          pybabel update -i messages.pot -d locale
      - name: Count incomplete translations
        shell: bash
        run: |
          output=$(find . -name LC_MESSAGES -exec pocount --incomplete --short "{}" +)
          echo $output
          [ "$output" = "" ]
