name: Translations
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install translate-toolkit for pocount
        run: |
          sudo apt update
          sudo apt install translate-toolkit
      - run: pip install -r requirements.txt
      - name: Update catalogs
        working-directory: extension_explorer
        run: |
          pybabel extract -F babel.cfg -o messages.pot .
          pybabel update -i messages.pot -d translations
      - name: Count incomplete translations
        run: |
          output=$(find . -name LC_MESSAGES -exec pocount --incomplete --short "{}" +)
          echo $output
          [ "$output" = "" ]
